# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import event_imager_pb2 as event__imager__pb2


class EventImagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getTicketUrl = channel.unary_unary(
                '/event_imager.EventImager/getTicketUrl',
                request_serializer=event__imager__pb2.EventEviteTicketInput.SerializeToString,
                response_deserializer=event__imager__pb2.EventEviteTicketInfo.FromString,
                )


class EventImagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getTicketUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventImagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getTicketUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.getTicketUrl,
                    request_deserializer=event__imager__pb2.EventEviteTicketInput.FromString,
                    response_serializer=event__imager__pb2.EventEviteTicketInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'event_imager.EventImager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EventImager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getTicketUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/event_imager.EventImager/getTicketUrl',
            event__imager__pb2.EventEviteTicketInput.SerializeToString,
            event__imager__pb2.EventEviteTicketInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
