# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event-imager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65vent-imager.proto\x12\x0c\x65vent_imager\":\n\x14\x45ventEviteTicketInfo\x12\x0f\n\x07\x65viteId\x18\x01 \x01(\t\x12\x11\n\tticketUrl\x18\x02 \x01(\t\"P\n\x14\x45ventEviteTicketMeta\x12\x0e\n\x06qrSize\x18\x01 \x01(\t\x12\x13\n\x0bqrPositionY\x18\x02 \x01(\t\x12\x13\n\x0bqrPositionX\x18\x03 \x01(\t\"q\n\x15\x45ventEviteTicketInput\x12\x0f\n\x07\x65ventId\x18\x01 \x01(\t\x12\x0f\n\x07\x65viteId\x18\x02 \x01(\t\x12\x36\n\nticketMeta\x18\x03 \x01(\x0b\x32\".event_imager.EventEviteTicketMeta2h\n\x0b\x45ventImager\x12Y\n\x0cgetTicketUrl\x12#.event_imager.EventEviteTicketInput\x1a\".event_imager.EventEviteTicketInfo\"\x00\x62\x06proto3')



_EVENTEVITETICKETINFO = DESCRIPTOR.message_types_by_name['EventEviteTicketInfo']
_EVENTEVITETICKETMETA = DESCRIPTOR.message_types_by_name['EventEviteTicketMeta']
_EVENTEVITETICKETINPUT = DESCRIPTOR.message_types_by_name['EventEviteTicketInput']
EventEviteTicketInfo = _reflection.GeneratedProtocolMessageType('EventEviteTicketInfo', (_message.Message,), {
  'DESCRIPTOR' : _EVENTEVITETICKETINFO,
  '__module__' : 'event_imager_pb2'
  # @@protoc_insertion_point(class_scope:event_imager.EventEviteTicketInfo)
  })
_sym_db.RegisterMessage(EventEviteTicketInfo)

EventEviteTicketMeta = _reflection.GeneratedProtocolMessageType('EventEviteTicketMeta', (_message.Message,), {
  'DESCRIPTOR' : _EVENTEVITETICKETMETA,
  '__module__' : 'event_imager_pb2'
  # @@protoc_insertion_point(class_scope:event_imager.EventEviteTicketMeta)
  })
_sym_db.RegisterMessage(EventEviteTicketMeta)

EventEviteTicketInput = _reflection.GeneratedProtocolMessageType('EventEviteTicketInput', (_message.Message,), {
  'DESCRIPTOR' : _EVENTEVITETICKETINPUT,
  '__module__' : 'event_imager_pb2'
  # @@protoc_insertion_point(class_scope:event_imager.EventEviteTicketInput)
  })
_sym_db.RegisterMessage(EventEviteTicketInput)

_EVENTIMAGER = DESCRIPTOR.services_by_name['EventImager']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EVENTEVITETICKETINFO._serialized_start=36
  _EVENTEVITETICKETINFO._serialized_end=94
  _EVENTEVITETICKETMETA._serialized_start=96
  _EVENTEVITETICKETMETA._serialized_end=176
  _EVENTEVITETICKETINPUT._serialized_start=178
  _EVENTEVITETICKETINPUT._serialized_end=291
  _EVENTIMAGER._serialized_start=293
  _EVENTIMAGER._serialized_end=397
# @@protoc_insertion_point(module_scope)
